//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xentry.Desktop.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string StringUserConnectedNameMDI {
            get {
                return ((string)(this["StringUserConnectedNameMDI"]));
            }
            set {
                this["StringUserConnectedNameMDI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string StringLogFile {
            get {
                return ((string)(this["StringLogFile"]));
            }
            set {
                this["StringLogFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("xEntry")]
        //Repertoire parent pour tous les fichiers de configuration | Celui correspondant au projet
        public string MasterDirectory {
            get {
                return ((string)(this["MasterDirectory"]));
            }
            set {
                this["MasterDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Log")]
        //Repertoire principal pour tous les fichiers de Log
        public string DirectoryUtilLog {
            get {
                return ((string)(this["DirectoryUtilLog"]));
            }
            set {
                this["DirectoryUtilLog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ConnectionString")]

        //Nom du repertoire qui contiendra la chaine de connexion a la BD
        public string DirectoryUtilConn {
            get {
                return ((string)(this["DirectoryUtilConn"]));
            }
            set {
                this["DirectoryUtilConn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UserSQLSever.txt")]
        //Nom du fichier qui contiendra la chaine de connexion connexion a la BD SQLServer
        public string FileSQLServer {
            get {
                return ((string)(this["FileSQLServer"]));
            }
            set {
                this["FileSQLServer"] = value;
            }
        }
    }
}
